services:
  - type: web
    name: browser-mcp-agent
    runtime: python
    region: Ohio
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: streamlit run main.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.cache/ms-playwright
